function g_struc=group_struc(id,type,c_mean,c_cov,center,ang,len,group_prior)
g_struc=struct('id',id,'type',type, ...
    'mean',c_mean,'cov',c_cov, ...
    'center',center,'ang',ang,'len',len,'group_prior',group_prior);
end