function prettyplot(hXLabel,hYLabel,legh)

if ~isnan(legh)
    M = findobj(legh,'type','line');
    m=findobj(legh);
    set([legh],'FontName'   , 'Helvetica','TextColor',[.3 .3 .3] )
end


set( gca                       , ...
    'FontName'   , 'Helvetica','FontSize',40 );
set([hXLabel hYLabel], ...
    'FontName'   , 'Helvetica','Color',[.3 .3 .3] );
set(gca,'box','off')
set([hXLabel hYLabel]  , ...
    'FontSize'   , 50          );
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );

% scale = 0.05;
% pos = get(gca, 'Position');
% pos(2) = pos(2)+scale*pos(4);
% pos(4) = (1-scale)*pos(4);
% set(gca, 'Position', pos)

hold off